branch-defaults:
  default:
    environment: null
    group_suffix: null
environment-defaults:
  ebtomcat-dev:
    branch: null
    repository: null
  ebtomcat-dev2:
    branch: null
    repository: null
global:
  application_name: ebtomcat
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
